name: emr
description: Electronic Medical Records Manager is a simple solution for managing medical records, patient information, appointments, etc. Created with Flutter, it can be installed on Windows, MacOS or Linux. It is simple, secure and robust. Add patients and appointments, manage medicine database, write and send prescriptions easily. It issecure as all the data is stored locally..

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  objectbox: ^1.0.0
  objectbox_flutter_libs: any
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  http: ^0.13.3
  desktop_window: ^0.4.0
  charts_flutter: ^0.10.0
  syncfusion_flutter_calendar: ^19.1.67
  draw_graph: ^1.0.0
  crypto: ^3.0.1
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  path_provider: ^2.0.2
  form_validator: ^0.1.7
  time_range_picker: ^2.0.1
  open_document: ^1.0.2
  dio: ^4.0.0
  open_file: ^3.2.1
  filepicker_windows: ^2.0.0
  permission_handler: ^8.1.1
  fluent_ui: ^2.1.1
  system_theme: ^1.0.1
  fluentui_system_icons: ^1.1.133
  msix: ^2.1.3
  bitsdojo_window: ^0.1.1+1
  flutter_acrylic: ^0.0.1
  get: ^4.1.4
  another_flushbar: ^1.10.23
  page_transition: ^2.0.2
  pdf: ^3.4.2

dev_dependencies:
  build_runner: ^1.0.0
  objectbox_generator: any

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/data/data.json
    - assets/data/appointment.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Black.ttf
        weight: 900
      - asset: fonts/Roboto-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: fonts/Roboto-Medium.ttf
        weight: 500
      - asset: fonts/Roboto-MediumItalic.ttf
        weight: 500
        style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
msix_config:
  display_name: EMR Manager
  publisher_display_name: DevNoobs
  identity_name: DevNoobs.EMR
  msix_version: 1.0.0.0
  # certificate_path: C:\flutter\.pub-cache\hosted\pub.dartlang.org\msix-2.1.3\lib\assets\test_certificate.pfx
  certificate_password: 1234
  publisher: CN=DevNoobs, O=DevNoobs, S=India, C=IN
  logo_path: C:\Users\Pratik Bedre\Downloads\report.png
  start_menu_icon_path: C:\Users\Pratik Bedre\Downloads\report.png
  tile_icon_path: C:\Users\Pratik Bedre\Downloads\medical.png
  icons_background_color: transparent
  architecture: x64
